In [44]:
import numpy as np


# 1.创建数组
# arange([start, ]stop, [step, ]dtype=None, *, like=None)
#     创建一维数组, 元素的值由区间[start, stop)内均匀间隔step构成. 参数列表如下:
#         start - int/float类型, 区间起步, 默认为0
#         stop - int/float类型, 区间结束
#         step - int/float类型, 间隔大小, 默认为1
#         dtype - dtype类型, 输出类型, 未指定时参考其他输入类型
print("\n" + "np.arange:")
print(np.arange(1, 10, 1))


# array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
#     创建多维数组, 元素的值由其他类似array的对象获得. 参数列表如下:
#         object - array_like类型, 创建数组的原始数据
#         dtype - data type类型, 指定元素的类型
print("\n" + "np.array:")
print(np.array([[1,2],[3,4]], dtype=np.float64))


# diag(v, k=0)
#     提取数组的对角线, 或构造对角线数组. 参数列表如下:
#         v - array_like类型, 当v为二维数组时, 提取v的k对角线; 当v为一维数组时, 使用v作为新数组的k对角线
#         k - int类型, 对角线位置, 0为主对角线, >0位于主对角线上方, <0位于主对角线下方
print("\n" + "np.diag:")
print(np.diag(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])))


# empty(shape, dtype=float, order='C', *, like=None)
#     创建多维数组, 元素的值直接为原内存的值. 参数列表如下:
#         shape - int/tuple类型, 数组的shape
#         dtype - data type类型. 默认为np.float64
#         order - str类型, 多维数组在内存的存放方式. 可选列表: 'C'(row-major)/'F'(column-major)
print("\n" + "np.empty:")
print(np.empty((2, 3), dtype=np.int32))


# eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
#     创建矩阵, 矩阵的对角线为1, 其余元素为0. 参数列表如下:
#         N - int类型, 矩阵的行数
#         M - int类型, 矩阵的列数
#         k - int类型, 指定对角线k的值, 0为主对角线, >0位于主对角线上方, <0位于主对角线下方
#         dtype - data type类型, 元素的类型
#         order - str类型, 元素在内存的排列方式. 可选列表: 'C'/'F'
print("\n" + "np.eye:")
print(np.eye(2, 3, dtype=np.int32))


# linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#     创建多维数组, 元素的值在空间[start, stop]上等间隔生成num份. 参数列表如下:
#         start - array_like类型, 区间起步
#         stop - array_like类型, 区间结束
#         num - int类型, 生成的份数, 必须为非负数
#         endpoint - bool类型, 区间是否包含stop
#         retstep - bool类型, 是否顺带返回step
#         dtype - data type类型, 元素的类型
#         axis - int类型, 此时start/stop必须为array_like, 区间内容沿指定轴(0沿y轴, 1沿x轴)
print("\n" + "np.linspace:")
print(np.linspace([0, 2, 3], [10, 12, 13], num=11, axis=0))


# ones(shape, dtype=None, order='C', *, like=None)
#     创建多维数组, 元素的值为1. 参数列表如下:
#         shape - tuple类型, 数组的shape
#         dtype - data type类型
#         order - str类型, 多维数组的存放方式. 可选值: 'C'/'F'
print("\n" + "np.ones:")
print(np.ones((2,3), order='F'))


# zeros(shape, dtype=float, order='C', *, like=None)
#     创建多维数组, 元素的值为0. 参数列表如下:
#         shape - tuple类型, 数组的shape
#         dtype - data type类型
#         order - str类型, 多维数组的存放方式. 可选值: 'C'/'F'
print("\n" + "np.zeros:")
print(np.zeros((3,2), dtype=np.int32))

# zeros_like(a, dtype=None, order='K', subok=True, shape=None)
#     创建与其他数组shape和dtype相同的多维数组, 元素的值为0. 参数列表如下:
#         a - ndarray类型, 新数组参考该数组的shape和dtype
#         dtype - data type类型, 重新指定dtype
#         order - str类型, 重新指定数组在内存的存放方式. 列表如下:
#             'C' - 使用C语言方式(row major)
#             'F' - 使用Fortran方式(column major)
#             'A' - 当a为'C'时, 数组使用'C'; 当a为'F'时, 数组使用'F'
#             'K' - 数组与a的存放方式接近
#         shape - int/sequence类型, 重新指定shape




np.arange:
[1 2 3 4 5 6 7 8 9]

np.array:
[[1. 2.]
 [3. 4.]]

np.diag:
[1 5 9]

np.empty:
[[         0 1072693248          0]
 [1073741824          0 1074266112]]

np.eye:
[[1 0 0]
 [0 1 0]]

np.linspace:
[[ 0.  2.  3.]
 [ 1.  3.  4.]
 [ 2.  4.  5.]
 [ 3.  5.  6.]
 [ 4.  6.  7.]
 [ 5.  7.  8.]
 [ 6.  8.  9.]
 [ 7.  9. 10.]
 [ 8. 10. 11.]
 [ 9. 11. 12.]
 [10. 12. 13.]]

np.ones:
[[1. 1. 1.]
 [1. 1. 1.]]

np.zeros:
[[0 0]
 [0 0]
 [0 0]]

meshgrid_01:
[[[1]]

 [[2]]

 [[3]]]
[[[11]
  [12]
  [13]
  [14]]]
[[[21 22 23 24 25]]]

meshgrid_02:
[[[1]
  [2]
  [3]]]
[[[11]]

 [[12]]

 [[13]]

 [[14]]]
[[[21 22 23 24 25]]]

meshgrid_03:
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]
[[[11 11 11 11 11]
  [12 12 12 12 12]
  [13 13 13 13 13]
  [14 14 14 14 14]]

 [[11 11 11 11 11]
  [12 12 12 12 12]
  [13 13 13 13 13]
  [14 14 14 14 14]]

 [[11 11 11 11 11]
  [12 12 12 12 12

In [47]:
import numpy as np

# 续1.创建数组
# meshgrid(*xi, copy=True, sparse=False, indexing='xy') --> ndarray, ndarray
#     从坐标向量生成坐标矩阵. 参数列表如下:
#         x1, x2, x3,... - 1D array-like类型, 用于生成矩阵的数组
#         copy - bool类型, 
#         sparse - bool类型, 是否不在其他维度进行广播
#         indexing - str类型, 生成的数组类型. 列表如下:
#             xy - 笛卡尔坐标. 默认值
#             ij - 矩阵
# 例1. 剖析原理(以sparse=True, indexing='ij'为例)
# np.array(x1).reshape(-1, 1, 1,...)
# np.array(x2).reshape(1, -1, 1,...)
# np.array(x3).reshape(1, 1, -1,...)
print("\n" + "meshgrid_01:")
x = np.linspace(1, 3, 3, dtype = np.int32)
y = np.linspace(11, 14, 4, dtype = np.int32)
z = np.linspace(21, 25, 5, dtype = np.int32)
x_1, y_1, z_1 = np.meshgrid(x, y, z, sparse=True, indexing='ij')
print(x_1)
print(y_1)
print(z_1)

# 例2. 剖析原理(以sparse=True, indexing='xy'为例, 调换x/y轴的shape)
# np.array(x1).reshape(1, -1, 1,...)
# np.array(x2).reshape(-1, 1, 1,...)
# np.array(x3).reshape(1, 1, -1,...)
print("\n" + "meshgrid_02:")
x_2, y_2, z_2 = np.meshgrid(x, y, z, sparse=True, indexing='xy')
print(x_2)
print(y_2)
print(z_2)

# 例3. 剖析原理(以sparse=False, indexing='ij'为例)
# np.array(x1).reshape(-1, len(x2), len(x3),...)
# np.array(x2).reshape(len(x1), -1, len(x3),...)
# np.array(x3).reshape(len(x1), len(x2), -1,...)
print("\n" + "meshgrid_03:")
x_3, y_3, z_3 = np.meshgrid(x, y, z, sparse=False, indexing='ij')
print(x_3)
print(y_3)
print(z_3)

# 例4. 剖析原理(以sparse=True, indexing='xy'为例, 调换x/y轴的shape)
# np.array(x1).reshape(len(x2), -1, len(x3),...)
# np.array(x2).reshape(-1, len(x1), len(x3),...)
# np.array(x3).reshape(len(x2), len(x1), -1,...)
print("\n" + "meshgrid_04:")
x_4, y_4, z_4 = np.meshgrid(x, y, z, sparse=False, indexing='xy')
print(x_4)
print(y_4)
print(z_4)


meshgrid_01:
[[[1]]

 [[2]]

 [[3]]]
[[[11]
  [12]
  [13]
  [14]]]
[[[21 22 23 24 25]]]

meshgrid_02:
[[[1]
  [2]
  [3]]]
[[[11]]

 [[12]]

 [[13]]

 [[14]]]
[[[21 22 23 24 25]]]

meshgrid_03:
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]
[[[11 11 11 11 11]
  [12 12 12 12 12]
  [13 13 13 13 13]
  [14 14 14 14 14]]

 [[11 11 11 11 11]
  [12 12 12 12 12]
  [13 13 13 13 13]
  [14 14 14 14 14]]

 [[11 11 11 11 11]
  [12 12 12 12 12]
  [13 13 13 13 13]
  [14 14 14 14 14]]]
[[[21 22 23 24 25]
  [21 22 23 24 25]
  [21 22 23 24 25]
  [21 22 23 24 25]]

 [[21 22 23 24 25]
  [21 22 23 24 25]
  [21 22 23 24 25]
  [21 22 23 24 25]]

 [[21 22 23 24 25]
  [21 22 23 24 25]
  [21 22 23 24 25]
  [21 22 23 24 25]]]

meshgrid_04:
[[[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]]

 [[1 1 1 1 1]
  [2

In [52]:
import numpy as np


# 2.数据操作
# concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
#     将多个相同shape的数组进行堆叠(copy). 参数列表如下:
#         a1, a2, ... - sequence类型, 多个相同shape的数组
#         axis - int/None类型, 沿指定的轴进行堆叠(0沿y轴, 1沿x轴). 为None时, 将所有数组进行伸展堆叠为一维数组
#         out - ndarray类型, 指定结果放置的地方, 该ndarray必须与结果shape一致
#         dtype - data type类型, 元素的类型. 不能与out一起指定
print("\n" + "np.concatenate:")
arr1 = np.zeros((2, 3))
arr2 = np.empty((2, 3))
print(np.concatenate((arr1, arr2), axis=0))


# sort(a, axis=- 1, kind=None, order=None)
#     对数组进行排序(copy). 参数列表如下:
#         a - array_like类型, 需要排序的数组
#         axis - int/None类型, 执行排序的轴(0沿y轴, 1沿x轴), None表示先将数组伸展为一维数组再排序, -1表示沿最后的轴排序
#         kind - str类型, 排序算法, 默认为quicksort. 可选列表: 'quicksort'/'mergesort'/'heapsort'/'stable'
#         order - str/list类型, 根据指定名称的关键字列进行排序
print("\n" + "np.sort:")
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)
print(np.sort(a, order='height'))


# split(arr, indices_or_sections, axis=0)
#     将数组进行分割(view). 参数列表如下:
#         arr - ndarray类型, 进行分割的数组
#         indices_or_sections - int/1D array_like类型, 当为int时, 将数组沿指定轴平均分割; 当为array_like时, 将数组沿指定轴按索引[:a_0
#], [a_0:a_1]...[a_n:]分割
#         axis - int类型, 沿指定的轴进行分割
rng = np.random.default_rng()      #参考np.random部分
arr = rng.standard_normal((3,4))   #参考np.random部分
print("\n" + "np.split:")
a, b, c = np.split(arr, [1, 3], axis=1)
print(a)
print(b)
print(c)


np.concatenate:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.sort:

np.split:
[[-0.03069062]
 [ 2.22675843]
 [ 0.61399481]]
[[-0.69833301 -0.86575443]
 [ 2.80828194 -0.5689653 ]
 [-2.21486613  1.18178542]]
[[ 0.19792845]
 [-0.8437264 ]
 [-0.11866621]]


In [73]:
import numpy as np


rng = np.random.default_rng()      #参考np.random部分
arr = rng.standard_normal((2,3))   #参考np.random部分
print(arr)
# 3.ndarray
# 1)ndarray的属性
# T
#    数组的转置(view)
print("\n" + "T:")
print(arr.T)

# ndim
#     数组的维度
print("ndim: " + str(arr.ndim))

# shape
#     数组的形状
print("shape: " + str(arr.shape))

# size
#     数组的元素个数
print("size: " + str(arr.size))


# 2)ndarray的方法
# argmax(axis=None, out=None, *, keepdims=False)
#     指定轴上最大值的索引. 参数列表如下:
#         axis - int/None类型, 沿指定轴的最大值(0沿y轴, 1沿x轴). 为None时, 先伸展为一维数组再比较
#         out - ndarray类型, 结果保存到指定数组. 该数组必须与结果的shape一致
#         keepdims - bool类型, 结果是否保持原来的维度
print("\n" + "ndarray.argmax:")
print(arr.argmax(axis=0))


# ravel(order='C')
#     数组伸展为一维数组(view). 参数列表如下:
#         order - str类型, 读取数组的优先顺序. 可选列表: 
#             'C' - C语言格式, 逐行读取
#             'F' - Fortran格式, 逐列读取
#             'A' - 当数组内容在内存中以Fortran格式存放, 以Fortran格式读取. 反之亦然
#             'K' - 当数组内容在内存中以何种格式存放, 便以何种格式读取
print("\n" + "ndarray.ravel:")
print(arr.ravel())


# reshape(shape, order='C')
#     调整数组的形状, 不改变元素值(view). 参数列表如下:
#         shape - int/tuple类型, 数组的目标形状
#         order - str类型, 数组在内存中的存放方式. 可选列表: 'C'/'F'/'A'
print("\n" + "np.reshape:")
print(arr.reshape((3,2)))


# resize(new_shape, refcheck=True)
#     调整数组的形状, 不改变元素值(in-place). 参数列表如下:
#         new_shape - int/tuple类型, 数组的目标形状
#         refcheck - bool类型, 是否检查调整前后数组size变化, 为False时可以改变size大小
print("\n" + "np.resize:")
arr.resize((5,2), refcheck=False)
print(arr)

[[ 0.63290555  0.89396061  0.30854444]
 [ 0.38947501 -1.59275547  0.65976773]]
T:[[ 0.63290555  0.38947501]
 [ 0.89396061 -1.59275547]
 [ 0.30854444  0.65976773]]
ndim: 2
shape: (2, 3)
size: 6

ndarray.argmax:
[0 0 1]

ndarray.ravel:
[ 0.63290555  0.89396061  0.30854444  0.38947501 -1.59275547  0.65976773]

np.reshape:
[[ 0.63290555  0.89396061]
 [ 0.30854444  0.38947501]
 [-1.59275547  0.65976773]]

np.resize:
[[ 0.63290555  0.89396061]
 [ 0.30854444  0.38947501]
 [-1.59275547  0.65976773]
 [ 0.          0.        ]
 [ 0.          0.        ]]


In [4]:
import numpy as np


# 4.索引/切片/花式索引/广播
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 索引
print("\n" + "index:")
ind = arr[0]
print(ind)


# 切片
print("\n" + "slice:")
sli = arr[1:3]
print(sli)
sli_2 = arr[:, :3]
print(sli_2)


# 花式索引
print("\n" + "fancy index:")
con = arr < 6
result = arr[arr < 6]
print(con)
print(result)

fancy = arr[[0, 1, 2], [3, 1, 2]]  # equal a[0, 3], a[1, 2], a[2, 2]
print(fancy)


# 广播
print("\n" + "broadcast:")
add = arr + 1
sub = arr - 2
multi = arr * 2
div = arr / 2
power = arr ** 2
print(add)
print(sub)
print(multi)
print(div)
print(power)

arr_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr_2)
print(arr_2 + [2, 3, 4])          #(4,3) and (3,)
broad = np.array([1, 0, 1, 0])
broad1 = broad[:, np.newaxis]
print(arr_2 + broad1)             #(4,3) and (4,1)


index:
[1 2 3 4]

slice:
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

fancy index:
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
[1 2 3 4 5]
[ 4  6 11]

broadcast:
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-1  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]
 [12 14 16]]
[[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]
 [10 11 12]]


In [3]:
import numpy as np


# 5.random模块
# default_rng()
#     返回Generator类
rng = np.random.default_rng()


# numpy.random.Generator类
# binomial(n, p, size=None)
#     二项式分布. 参数列表如下:
#         n - int/array_like类型, (n,p)中n的值
#         p - float/array_like类型, 独立事件出现的概率, 区间[0, 1]
#         size - int/tuple类型, 试验次数
print("\n" + "binomial:")
print(rng.binomial(10, 0.5, 100))   # 100次(10, 0.5)二项式分布中, 出现独立事件的次数


# integers(low, high=None, size=None, dtype=np.int64, endpoint=False)
#     生成多维数组, 内容为均匀分布的整数. 参数列表如下:
#         low - int/array_like类型, 起始值
#         high - int/array_like类型, 结束值. 当没有指定时, 区间为[0, low)
#         size - int/tuple类型, 生成内容的shape. 为None时, 生成单个值
#         dtype - data type类型, 元素的类型
#         endpoint - bool类型, 是否包含最高值
# ** 当为多维数组时, low/high至少一个的大小必须与列数相同
print("\n" + "integers:")
print(rng.integers([1, 15, 10], [10, 20, 30], (5, 3)))


# choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)
#     生成多维维数组. 参数如下:
#         a - 1D array-like/int类型, 为1维数组时, 从数组中抽取内容; 为int数组时, 将np.arange(a)结果作为1维数组源
#         size  - int/tuple类型, 指定输出的shape. 为None时, 返回单个值
#         replace - bool类型, 代表a中的元素是否可重复出现. True代表可重复出现
#         p - 1D array-line类型, 指定a中每个元素选取的概率. 为None时, 为均匀分布
print("\n" + "choice:")
print(rng.choice(9))


# normal(loc=0.0, scale=1.0, size=None)
#     正态分布数组. 参数列表如下:
#         loc - float/array_like类型, 正态分布的均值
#         scale - float/array_like类型, 正态分布的标准差
#         size - int/tuple类型, 生成数组的shape
# ** 当为多维数组时, loc/scale至少有一个与size的列数一致
print("\n" + "normal:")
print(rng.normal([0, 1, 2], 1, (2,3)))


# permutation(x, axis=0)
#     随机排列序列, 或使用range生成序列后再随机排序(copy). 参数列表如下:
#         x - int/array_like类型, 为int时, 使用np.arange生成序列, 然后打乱序列; 当为array_like时, 打乱序列
#         axis - int类型, 指定打乱序列的轴
arr1 = rng.integers(1, [20, 40, 60], (4, 3))
print("\n" + "permutation")
print(arr1)
result = rng.permutation(arr1, axis=0)
print(result)


# random(size=None, dtype=np.float64, out=None)
#     生成多维数组, 内容为均匀分布的区间为[0,1)的浮点数. 参数列表如下:
#         size - int/tuple类型, 生成内容的shape. 为None时, 返回单个值
#         dtype - data type类型, 只支持float32和float64
#         out - ndarray类型, 用于放置结果的数组, 数组的shape与元素类型必须与结果一致
print("\n" + "random:")
print(rng.random((2,3)))


# shuffle(x, axis=0)
#     打乱数组的内部排序(in-place). 参数列表如下:
#         x - ndarray/sequence类型, 目标数组或序列
#         axis - int类型, 指定打乱排序的轴
arr2 = rng.integers(1, [20, 40, 60], (4, 3))
print("\n" + "shuffle")
print(arr2)
rng.shuffle(arr2, axis=0)
print(arr2)


# standard_normal(size=None, dtype=np.float64, out=None)
#     生成标准正态分布. 参数列表如下:
#         size - int/tuple类型, 生成内容的shape. 为None时, 生成单个值
#         dtype - dtype类型, 只支持float32和float64
#         out - 备用的用于存放结果的数组, 指定时, 该数组的size与dtype必须与结果一致
print("\n" + "standard_normal:")
print(rng.standard_normal((2,3)))



#新旧版本(numpy 1.17前后)对比:
#===========================================
#random           random.Generator
#-------------------------------------------
#binomial         binomial
#choice           choice
#exponential      exponential
#normal           normal
#permutation      permutation
#randint          integers
#randn            standard_normal
#shuffle          shuffle
#===========================================


binomial:
[ 5  6  6  4  7  4  5  7  4  4  5  3  4  6  5  3  7  4  4  5  7  4  5  6
  4  7  7  5  3  2  5  5  7  6  7  4  3  3  7  5  8  3  3  6  5  5  4  6
  5  4  6  5  2  2 10  8  5  3  4  5  6  6  5  5  4  6  6  5  6  6  4  4
  6  7  8  5  5  9  3  7  5  5  6  3  3  5  5  6  4  6  5  3  5  4  6  5
  6  8  4  3]

integers:
[[ 8 18 12]
 [ 7 16 10]
 [ 6 18 13]
 [ 9 17 11]
 [ 6 17 23]]

choice:
8

normal:
[[ 0.8458822   1.36918434  1.74734798]
 [ 0.49872367 -0.11295399  0.60021599]]

permutation
[[17  2 35]
 [13  4 43]
 [11 11 58]
 [17  8 15]]
[[17  8 15]
 [11 11 58]
 [13  4 43]
 [17  2 35]]

random:
[[0.63757183 0.76326164 0.14778542]
 [0.2441265  0.75626446 0.13842262]]

shuffle
[[ 7 24  5]
 [16 25 11]
 [13 11 21]
 [ 2 25 17]]
[[13 11 21]
 [ 2 25 17]
 [ 7 24  5]
 [16 25 11]]

standard_normal:
[[ 0.84462286 -0.00197899 -0.76892808]
 [ 0.19016909  0.16210979  0.48512556]]


最后编辑于: 2022-09-13