In [7]:
# 例1. 广播
import numpy as np

a = [1,2,3,4]
b = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
array_a = np.array(a)
array_b = np.array(b)
array_c = array_a + array_b
print(array_c)

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [8]:
# 例2. 原子级操作
import numpy as np

L = range(1000)
%timeit [i**2 for i in L]

a = np.arange(1000)
%timeit a**2

158 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
776 ns ± 1.96 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
