In [1]:
# 例1. 转置矩阵、矩阵的行列式、矩阵的逆
import numpy as np
from scipy import linalg

# 转置矩阵
a = np.arange(12).reshape(3,4)
print(a)
print(a.T)

# 行列式
b = [[1, 2], [3, 4]]
print(linalg.det(b))

# 矩阵的逆
print(linalg.inv(b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
-2.0
[[-2.   1. ]
 [ 1.5 -0.5]]


In [2]:
# 例2. PLU分解
from scipy import linalg

A = [[2, 4, 5, -2], [-4, -5, -8, 1], [2, -5, 1, 8], [-6, 0, -3, 1]]
P, L, U = linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [-0.33333333  1.          1.          0.        ]
 [-0.33333333 -0.8        -0.13333333  1.        ]]
[[-6.          0.         -3.          1.        ]
 [ 0.         -5.         -6.          0.33333333]
 [ 0.          0.          6.          8.        ]
 [ 0.          0.          0.         -0.33333333]]


In [3]:
# 例3.求积分
from scipy import integrate
import math

def exp_inte(x, a):
    return a*math.pow(x,2)

print(integrate.quad(exp_inte,2,6,args=(3,)))

(208.0, 2.3092638912203256e-12)
